<div class="newsletter-subscribe">
    <h2>Contact permission</h2>
    <p>We'd love to send you exclusive offers and the latest info about our novelties and sales by email. We'll always treat your personal details with the utmost care and will never sell them to other companies for marketing purposes.</p>
    <p>
        <input type="radio" id="newsletter-subscribe" name="newsletter-subscribe" value="1" />
        <label for="newsletter-subscribe">Yes please, i'd like to be subscribed to news, offers and promotions.</label>
    </p>
    <p>
        <input type="radio" id="newsletter-nosubscribe" name="newsletter-subscribe" value="0" />
        <label for="newsletter-nosubscribe">No, I want to miss everything. Don't subscribe me.</label>
    </p>
</div>
